# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Mage Action'
description: 'GitHub Action for Mage, a Make/rake-like build tool using Go'
author: 'crazy-max'
branding:
  color: 'purple'
  icon: 'settings'

inputs:
  version:
    description: 'Mage version.'
    default: 'latest'
    required: false
  args:
    description: 'Arguments to pass to Mage'
    required: false
  workdir:
    description: 'Working directory (below repository root)'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
